//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.08.04 at 09:20:04 PM IST 
//


package com.tiaa.dto;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for branchType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="branchType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="location" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="totalcollection" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="locationid" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="sumoforder" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "branchType", propOrder = {
    "location",
    "totalcollection",
    "locationid",
    "sumoforder"
})
public class BranchType {

    @XmlElement(required = true)
    protected String location;
    protected float totalcollection;
    @XmlElement(required = true)
    protected String locationid;
    protected Float sumoforder;

    /**
     * Gets the value of the location property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLocation() {
        return location;
    }

    /**
     * Sets the value of the location property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLocation(String value) {
        this.location = value;
    }

    /**
     * Gets the value of the totalcollection property.
     * 
     */
    public float getTotalcollection() {
        return totalcollection;
    }

    /**
     * Sets the value of the totalcollection property.
     * 
     */
    public void setTotalcollection(float value) {
        this.totalcollection = value;
    }

    /**
     * Gets the value of the locationid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLocationid() {
        return locationid;
    }

    /**
     * Sets the value of the locationid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLocationid(String value) {
        this.locationid = value;
    }

    /**
     * Gets the value of the sumoforder property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getSumoforder() {
        return sumoforder;
    }

    /**
     * Sets the value of the sumoforder property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setSumoforder(Float value) {
        this.sumoforder = value;
    }

}
